accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from rest_framework.routers import DefaultRouter

from accounts.api_views import UserViewSet
from accounts.views import signup, UserView, update_token_ajax

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login/'), name='logout'),
    path('profile/',  login_required(UserView.as_view()), name='profile'),
    path('signup/', signup, name='signup'),
    path('update-token-ajax/', login_required(update_token_ajax)),
]

router = DefaultRouter()

router.register(r'users', UserViewSet)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from accounts.urls import router as accounts_router
from recipe_book.urls import router as recipe_book_router

app_name = 'recipe_book_api'

router = DefaultRouter()
router.registry.extend(accounts_router.registry)
router.registry.extend(recipe_book_router.registry)

urlpatterns = [
    path('', include('recipe_book.urls', namespace='recipe_book')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_book/urls.py
from django.urls import path, re_path
from rest_framework.routers import DefaultRouter

from recipe_book.api_views import RecipeViewSet, IngredientViewSet, RecipeIngredientViewSet, StepViewSet
from recipe_book.views import IndexView, RecipesListView, AboutAsTemplateView, RecipeFormView

app_name = 'recipe_book'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    re_path(r'^recipe/(?P<mode>add|view|edit|delete)/(?P<pk>\d+)?$', RecipeFormView.as_view(), name='recipe'),
    path('recipes/', RecipesListView.as_view(), name='recipes'),
    path('about_us/', AboutAsTemplateView.as_view(), name='about_us'),
]

router = DefaultRouter()

router.register(r'recipes', RecipeViewSet)
router.register(r'ingredients', IngredientViewSet)
router.register(r'recipe-ingredients', RecipeIngredientViewSet)
router.register(r'steps', StepViewSet)

templates/back_to_top.html
<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"><i class="bi bi-arrow-up"></i></a>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <title>{{ title_prefix|default:'Книга Рецептов - ' }}{{ title }}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&family=Lora:wght@600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    {% include "spinner.html" %}
    {% include "navbar.html" %}
    {% include "page_header.html" %}

    {% block content %}{% endblock %}

    {% include "footer.html" %}
    {% include "back_to_top.html" %}

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{%  static 'js/main.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>

</html>

templates/carousel.html
{% load static %}

<!-- Carousel Start -->
<div class="container-fluid p-0 mb-5 wow fadeIn" data-wow-delay="0.1s">
    <div id="header-carousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="w-100" src="{% static 'img/carousel-1.jpg' %}" alt="Image">
                <div class="carousel-caption">
                    <div class="container">
                        <div class="row justify-content-start">
                            <div class="offset-lg-2 col-lg-7">
                                <h2 class="display-2 mb-5 animated slideInDown">Органическая Пища Полезна Для Здоровья</h2>
                                <a href="{% url 'recipe_book:recipes' %}" class="btn btn-primary rounded-pill py-sm-3 px-sm-5">Рецепты</a>
                                <a href="{% url 'recipe_book:recipe' mode='add' pk=pk %}" class="btn btn-secondary rounded-pill py-sm-3 px-sm-5 ms-3">Добавить Рецепт</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
                <div class="carousel-caption">
                    <div class="container">
                        <div class="row justify-content-start">
                            <div class="offset-lg-2 col-lg-7">
                                <h2 class="display-2 mb-5 animated slideInDown">Натуральная Пища Всегда Полезна Для Здоровья</h2>
                                <a href="{% url 'recipe_book:recipes' %}" class="btn btn-primary rounded-pill py-sm-3 px-sm-5">Рецепты</a>
                                <a href="{% url 'recipe_book:recipe' mode='add' pk=pk %}" class="btn btn-secondary rounded-pill py-sm-3 px-sm-5 ms-3">Добавить Рецепт</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Назад</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#header-carousel"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Далее</span>
        </button>
    </div>
</div>
<!-- Carousel End -->

templates/footer.html
{% load static %}

<!-- Footer Start -->
<div class="container-fluid bg-dark footer mt-5 pt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container-fluid copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a href="{% url 'recipe_book:index' %}">Книга Рецептов</a>, Все Права Защищены.
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <!--/*** This template is free as long as you keep the footer author’s
                     credit link/attribution link/backlink. If you'd like to use the template without
                      the footer author’s credit link/attribution link/backlink, you can purchase
                       the Credit Removal License from "https://htmlcodex.com/credit-removal".
                        Thank you for your support. ***/-->
                    {# https://htmlcodex.com/organic-food-website-template/ #}
                    {# https://htmlcodex.com/downloading/?item=2463 #}
                    Designed By: <a href="https://htmlcodex.com" target="_blank">HTML Codex</a>
                    <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

templates/navbar.html
{% load static %}
{% load nav_items %}
{% load user_greeting %}
<!-- Navbar Start -->
<div class="container-fluid fixed-top px-0 wow fadeIn" data-wow-delay="0.1s">
    {% include 'top_bar.html' %}
    {% url 'recipe_book:index' as index_path %}
    <nav class="navbar navbar-expand-lg navbar-light py-lg-0 px-lg-5 wow fadeIn" data-wow-delay="0.1s">
        <a {% if index_path != request.path %}href="{{ index_path }}"{% endif %} class="navbar-brand ms-4 ms-lg-0">
            <h1 class="fw-bold text-primary m-0">
                <span class="text-secondary">К</span>нига <span class="text-secondary">Р</span>ецептов
            </h1>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                {% get_nav_items as nav_items %}
                {% for item in nav_items %}
                    <a {% if item.link != request.path %}href="{{ item.link }}"{% endif %} class="nav-item nav-link">
                        {{ item.title }}
                    </a>
                {% endfor %}
            </div>
            <div class="d-none d-lg-flex ms-2">
                {% if user.is_authenticated %}
                    <span class="p-1 ms-3">{{ user|greeting }}</span>
                    <a class="btn-sm-square bg-white rounded-circle ms-3" href="{% url 'accounts:profile' %}">
                        <small class="fa fa-user text-body"></small>
                    </a>
                    <a class="btn-sm-square bg-white rounded-circle ms-3" href="{% url 'accounts:logout' %}">
                        <small class="fa fa-sign-out-alt text-body"></small>
                    </a>
                {% else %}
                    <a class="btn-sm-square bg-white rounded-circle ms-3" href="{% url 'accounts:login' %}">
                        <small class="fa fa-sign-in-alt text-body"></small>
                    </a>
                    <a class="btn-sm-square bg-white rounded-circle ms-3" href="{% url 'accounts:signup' %}">
                        <small class="fa fa-user-plus text-body"></small>
                    </a>
                {% endif %}
            </div>

            {% include 'tool_bar.html' %}
        </div>
    </nav>
</div>
<!-- Navbar End -->

templates/page_header.html
{% url 'recipe_book:index' as index_url %}
{% if request.path != index_url %}
<!-- Page Header Start -->
<div class="container-fluid page-header mb-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container">
        <h2 class="display-3 mb-3 animated slideInDown">{{ title }}</h2>
    </div>
</div>
<!-- Page Header End -->
{% endif %}

templates/spinner.html
<!-- Spinner Start -->
<div id="spinner"
     class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" role="status"></div>
</div>
<!-- Spinner End -->

templates/tool_bar.html
<div class="d-none d-lg-flex ms-2">
    {% if user.is_authenticated %}
        <a class="btn-sm-square bg-white rounded-circle ms-3" href="{% url 'recipe_book:recipe' mode='add' pk=pk %}"
           title="Добавит рецепт">
            <small class="fa fa-plus text-body"></small>
        </a>
    {% endif %}
</div>

templates/top_bar.html
{#<div class="top-bar row gx-0 align-items-center d-none d-lg-flex"></div>#}